/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Vongola
 */
public class EscogerPeliculaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form EscogerPaginaJFrame
     */
    public EscogerPeliculaJFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreUsuariojLabel = new javax.swing.JLabel();
        cerrarSesionjLabel = new javax.swing.JLabel();
        JLabelCoco = new javax.swing.JLabel();
        JFerdinand = new javax.swing.JLabel();
        JIT = new javax.swing.JLabel();
        JJumanji = new javax.swing.JLabel();
        escogerPaginaBGJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 800, 472));
        setMaximumSize(new java.awt.Dimension(800, 472));
        setMinimumSize(new java.awt.Dimension(800, 472));
        setResizable(false);
        getContentPane().setLayout(null);

        nombreUsuariojLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuariojLabel.setText("NOMBREDEUSUARIO");
        getContentPane().add(nombreUsuariojLabel);
        nombreUsuariojLabel.setBounds(105, 5, 101, 14);

        cerrarSesionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/BotonSalir.png"))); // NOI18N
        cerrarSesionjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarSesionjLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cerrarSesionjLabelMouseReleased(evt);
            }
        });
        getContentPane().add(cerrarSesionjLabel);
        cerrarSesionjLabel.setBounds(644, 0, 160, 38);

        JLabelCoco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PortadasPeliculas/Coco.PNG"))); // NOI18N
        JLabelCoco.setText("Coco");
        getContentPane().add(JLabelCoco);
        JLabelCoco.setBounds(70, 130, 150, 230);

        JFerdinand.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PortadasPeliculas/Ferdinan.PNG"))); // NOI18N
        JFerdinand.setText("Ferdinand");
        getContentPane().add(JFerdinand);
        JFerdinand.setBounds(240, 130, 150, 230);

        JIT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PortadasPeliculas/IT.PNG"))); // NOI18N
        JIT.setText("IT");
        getContentPane().add(JIT);
        JIT.setBounds(410, 130, 150, 230);

        JJumanji.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PortadasPeliculas/Jumanji.PNG"))); // NOI18N
        JJumanji.setText("Jumanji");
        getContentPane().add(JJumanji);
        JJumanji.setBounds(580, 130, 160, 230);

        escogerPaginaBGJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/EscogerPeliBG.png"))); // NOI18N
        escogerPaginaBGJLabel.setToolTipText("");
        getContentPane().add(escogerPaginaBGJLabel);
        escogerPaginaBGJLabel.setBounds(0, 0, 800, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionjLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionjLabelMousePressed
        // TODO add your handling code here:
        cerrarSesionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/BotonSalir" + "Presionado.png")));
    }//GEN-LAST:event_cerrarSesionjLabelMousePressed

    private void cerrarSesionjLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionjLabelMouseReleased
        // TODO add your handling code here:
        cerrarSesionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/BotonSalir" + ".png")));
    }//GEN-LAST:event_cerrarSesionjLabelMouseReleased

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EscogerPeliculaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EscogerPeliculaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EscogerPeliculaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EscogerPeliculaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new EscogerPeliculaJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JFerdinand;
    public javax.swing.JLabel JIT;
    public javax.swing.JLabel JJumanji;
    public javax.swing.JLabel JLabelCoco;
    public javax.swing.JLabel cerrarSesionjLabel;
    private javax.swing.JLabel escogerPaginaBGJLabel;
    public javax.swing.JLabel nombreUsuariojLabel;
    // End of variables declaration//GEN-END:variables
}
