/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author Vongola
 */
public class EscogerLugarJFrame extends javax.swing.JFrame {
    private ArrayList<JLabel> listaAsientos = new ArrayList<>();
    private int index = 0;
    /**
     * Creates new form EscogerLugarJFrame
     */
    public EscogerLugarJFrame() {
        initComponents();
        setLocationRelativeTo(null);
        for (int i = 0; i < 100; i++) {
            JLabel asiento = new JLabel();
            asiento.setName(i + "");
            asiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/asientoVerde.png")));
            JPanelAsientos.add(asiento);
            listaAsientos.add(asiento);
            JPanelAsientos.updateUI();
        }
    }

    public ArrayList<JLabel> getListaAsientos() {
        return listaAsientos;
    }

    public void setListaAsientos(ArrayList<JLabel> listaAsientos) {
        this.listaAsientos = listaAsientos;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombreUsuariojLabel = new javax.swing.JLabel();
        cerrarSesionjLabel = new javax.swing.JLabel();
        JPanelAsientos = new javax.swing.JPanel();
        EscogerLugarBGjLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setBounds(new java.awt.Rectangle(0, 0, 800, 755));
        setMaximumSize(new java.awt.Dimension(800, 755));
        setMinimumSize(new java.awt.Dimension(800, 755));
        setPreferredSize(new java.awt.Dimension(800, 755));
        setResizable(false);
        getContentPane().setLayout(null);

        nombreUsuariojLabel.setForeground(new java.awt.Color(255, 255, 255));
        nombreUsuariojLabel.setText("NOMBREDEUSUARIO");
        getContentPane().add(nombreUsuariojLabel);
        nombreUsuariojLabel.setBounds(105, 5, 101, 14);

        cerrarSesionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/BotonSalir.png"))); // NOI18N
        cerrarSesionjLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarSesionjLabelMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerrarSesionjLabelMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cerrarSesionjLabelMouseReleased(evt);
            }
        });
        getContentPane().add(cerrarSesionjLabel);
        cerrarSesionjLabel.setBounds(644, 0, 160, 38);

        JPanelAsientos.setLayout(new java.awt.GridLayout(0, 10));
        getContentPane().add(JPanelAsientos);
        JPanelAsientos.setBounds(100, 130, 620, 510);

        EscogerLugarBGjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/EscogerLugarBG.png"))); // NOI18N
        EscogerLugarBGjLabel.setMaximumSize(new java.awt.Dimension(800, 733));
        EscogerLugarBGjLabel.setMinimumSize(new java.awt.Dimension(800, 733));
        EscogerLugarBGjLabel.setPreferredSize(new java.awt.Dimension(800, 733));
        getContentPane().add(EscogerLugarBGjLabel);
        EscogerLugarBGjLabel.setBounds(0, 0, 800, 733);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cerrarSesionjLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionjLabelMousePressed
        // TODO add your handling code here:
        cerrarSesionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/BotonSalir" + "Presionado.png")));
    }//GEN-LAST:event_cerrarSesionjLabelMousePressed

    private void cerrarSesionjLabelMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionjLabelMouseReleased
        // TODO add your handling code here:
        cerrarSesionjLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imgs/BotonSalir" + ".png")));
    }//GEN-LAST:event_cerrarSesionjLabelMouseReleased

    private void cerrarSesionjLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarSesionjLabelMouseClicked

    }//GEN-LAST:event_cerrarSesionjLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(EscogerLugarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(EscogerLugarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(EscogerLugarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(EscogerLugarJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EscogerLugarJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel EscogerLugarBGjLabel;
    public javax.swing.JPanel JPanelAsientos;
    public javax.swing.JLabel cerrarSesionjLabel;
    public javax.swing.JLabel nombreUsuariojLabel;
    // End of variables declaration//GEN-END:variables
}
